import Head from "next/head";
import Nav from "@/components/Nav";
import ProductListings from "@/components/ProductListings";
import { getAllProductsInCollection } from "@/lib/shopify";
import styles from "../styles/Home.module.css";
import StoreHeading from "@/components/StoreHeading";
import Footer from "@/components/Footer";

function IndexPage({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className={styles.main}>
        <StoreHeading />
        <ProductListings products={products} />
      </main>
      <Footer />
    </div>
  );
}
// cool :-)
export async function getStaticProps() {
  const products = await getAllProductsInCollection();

  return {
    props: {
      products,
    },
  };
}

export default IndexPage;
